apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:   
  ports:
    - protocol: TCP
      port: 11211             
      targetPort: 11211
  selector:
    app: vpromc 
  type: ClusterIP
         