apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:   
  ports:
    - protocol: TCP
      port: 5672             
      targetPort: 5672
  selector:
    app: vprormq 
  type: ClusterIP
         